#
# Stack
#
ARG ELIXIR_VERSION=1.14.0
ARG OTP_VERSION=24.3.4
ARG DEBIAN_VERSION=bullseye-20210902-slim

ARG ELIXIR_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

#
# Runner
#
FROM ${ELIXIR_IMAGE}

ENV MIX_ENV test

WORKDIR /app

COPY . .

# Installing hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Installing deps
RUN mix deps.get

# Move the entrypoint script
COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

# Installing curl to ping neo4j
RUN apt-get update -y && \
    apt-get install curl -y

# Here we go
ENTRYPOINT [ "./entrypoint.sh" ]
CMD ["mix", "test"]