#
# Stack
#
ARG ELIXIR_VERSION=1.14.0
ARG OTP_VERSION=24.3.4
ARG DEBIAN_VERSION=bullseye-20210902-slim

ARG ELIXIR_IMAGE="hexpm/elixir:${ELIXIR_VERSION}-erlang-${OTP_VERSION}-debian-${DEBIAN_VERSION}"

#
# Runner
#
FROM ${ELIXIR_IMAGE}

# Installing curl to ping neo4j
RUN apt-get update -y && \
    apt-get install curl -y

WORKDIR /app

# Move the entrypoint script
COPY entrypoint.sh entrypoint.sh
RUN chmod +x entrypoint.sh

# Installing hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

ENV MIX_ENV="test"

COPY mix.exs mix.lock ./
RUN mix deps.get --only $MIX_ENV
RUN mkdir config

# copy compile-time config files before we compile dependencies
# to ensure any relevant config change will trigger the dependencies
# to be re-compiled.
COPY config/config.exs config/${MIX_ENV}.exs config/
RUN mix deps.compile

COPY config config
COPY lib lib

# Changes to config/runtime.exs don't require recompiling the code
COPY config/runtime.exs config/

# Compile the project
RUN mix compile

COPY test test

# Here we go
ENTRYPOINT [ "./entrypoint.sh" ]
CMD ["mix", "test"]
