Mox.defmock(OhMyAdolf.HTTPClientMock, for: HTTPoison.Base)
Mox.defmock(OhMyAdolf.RepoMock, for: OhMyAdolf.RepoBehavior)
Mox.defmock(OhMyAdolf.Wiki.WikiURLMock, for: OhMyAdolf.Wiki.WikiURLBehavior)
Mox.defmock(OhMyAdolf.Wiki.FetcherMock, for: OhMyAdolf.Wiki.FetcherBehavior)
Mox.defmock(OhMyAdolf.Wiki.ParserMock, for: OhMyAdolf.Wiki.ParserBehavior)
Mox.defmock(OhMyAdolf.Wiki.ScraperMock, for: OhMyAdolf.Wiki.ScraperBehavior)
Mox.defmock(OhMyAdolf.Wiki.PathsMock, for: OhMyAdolf.Wiki.PathsBehavior)
Mox.defmock(OhMyAdolf.Wiki.CrawlerMock, for: OhMyAdolf.Wiki.CrawlerBehavior)
