import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :oh_my_adolf, OhMyAdolfWeb.Endpoint,
  cache_static_manifest: "priv/static/cache_manifest.json"

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.

config :bolt_sips, Bolt,
  url: System.get_env("NEO4J_URL"),
  timeout: 45_000,
  retry_linear_backoff: [delay: 150, factor: 2, tries: 3],
  pool_size: 20,
  basic_auth: [
    username: System.get_env("NEO4J_USERNAME"),
    password: System.get_env("NEO4J_PASSWORD")
  ]
